# Generated by Django 2.2.3 on 2019-07-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0003_partener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partener',
        ),
    ]
