# Generated by Django 2.2.3 on 2019-07-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('group', models.CharField(max_length=64)),
            ],
        ),
    ]
